### ISSUE TITLE
I love the Readme!

### ISSUE THREAD

**Issue by Gitoffthelawn** [gildas-lormeau/SingleFile-Lite#2]
The readme deserves to be on the front page of every tech blog & magazine site.

Well done!

**Comment by gildas-lormeau** [comment]
Thank you :-)

**Comment by andrey-jef** [comment]
Hopped in here from today HN post. The readme shows what sarcasm is, as Sheldon said in Big Bang Theory 🤣

**Comment by mdesantis** [comment]
Sarcasm is still something even in 2022! Lovin' it!

**Comment by chirag127** [comment]
I think "Notable features of SingleFile Lite" can also be mentioned in the Benefits of the Manifest V3 as they all improve the performance of the browser and the security for the users.

**Comment by gildas-lormeau** [comment]
@ImportTaste I agree, but the last problem I couldn't circumevnt is still terrible.

**Comment by Gitoffthelawn** [comment]
@gildas-lormeau As an optimist, I'm all in favour of pessimism.
