### ISSUE TITLE
Possible circumvention of 5minutes limitation

### ISSUE THREAD

**Issue by raed667** [gildas-lormeau/SingleFile-Lite#9]
As long as you have at least one tab open.

You can inject a content-script into the page, that will periodically `ping` the service worker to keep it alive.

This is an ugly hack, but could help with `save time limited to 5 minutes max`.

Other extensions have already some implementations:

https://github.com/AdguardTeam/AdGuardMV3/blob/master/src/content-scripts/index.ts#L11

**Comment by gildas-lormeau** [comment]
Thank you very much for the information! I agree it's a ugly hack but, if I have to, I'll use a similar hack.

**Comment by raed667** [comment]
Thanks for taking the suggestion. Closing as not to clutter issues.

**Comment by gildas-lormeau** [comment]
I'm wondering is this techniques really works. AFAIK, the service worker will be stopped after 5 minutes anyway but the PING message will allow it to be restarted ASAP. It's OK if the content script is stateless or if it can serialize and save its state. Unfortunately, this is not the case in SingleFile. 
However, it should be possible to use the [native messaging API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) (i.e. SingleFile Companion) to circumvent this issue with the same technique. However, it seems it's buggy as well, see https://crbug.com/1152255.

**Comment by gildas-lormeau** [comment]
I posted an answer but I deleted it because it was irrelevant. Actually, after reflection, I think SingleFile is not impacted by this limitation, as long as the content script can run more than 5 minutes.
